### ISSUE TITLE
Investigate comments that aren't getting replies

### ISSUE THREAD

**Issue by joegoldbeck** [techforwarren/warren-plan-bot#104]
https://www.reddit.com/r/ElizabethWarren/comments/czfgi4/hi_im_the_warrenplanbot/eyyw8lg/
(This is a new account created by someone just to test out the bot)

https://www.reddit.com/r/ElizabethWarren/comments/czfgi4/hi_im_the_warrenplanbot/eyyhlzk/

**Comment by joegoldbeck** [comment]
Those comments don't seem to be showing up in `pushshift`, which would certainly cause it...

`curl "https://api.pushshift.io/reddit/comment/search?fields=author,author_fullname,body,created_utc,id,link_id,locked,parent_id,permalink,subreddit,subreddit_id&subreddit=elizabethwarren&q=warrenplanbot"`

**Comment by Hucxley** [comment]
Maybe getting automoderated due to the lack of karma since it's a new
account Just like our bot did when it first released.

**Comment by joegoldbeck** [comment]
It's possible! I can see the comment though. How can we confirm one way or another?

**Comment by joegoldbeck** [comment]
I don't think I've seen this happen again since the original post, so closing for now
