### ISSUE TITLE
Some of the plans on the EW site are abbreviated

### ISSUE THREAD

**Issue by Hucxley** [techforwarren/warren-plan-bot#116]
Some of the plans are consistent with the clustering concept, and have a summary before linking to a couple of plans posted on medium.

I'm not sure we need to abandon medium just yet, as I think they'll keep publishing there. I think we may need to look in both places and possibly use it as a guide to a cluster.

**Comment by joegoldbeck** [comment]
Looking at cleaning up the issues board so it's easier to find priority work to do, and I think we should close this for now! 

I don't think it's clear what the _action_ would be here, or if/how it would improve bot performance as it's currently being used. Can always reopen later if we have a concrete reason to do it and a plan for what "done" would look like :D

**Comment by Hucxley** [comment]
Agree to close as the plans page is getting more fleshed out now.
