### ISSUE TITLE
Operation Request: Response for "why should I support Warren?"

### ISSUE THREAD

**Issue by Hucxley** [techforwarren/warren-plan-bot#124]
From the moderators on Reddit, who apparently get this question a lot:

Hey there WarrenPlanBot [devs]! We were talking about a common question we have, which is "why should I support Warren?" Do you think there's a way to auto post a link to her plans or perhaps other popular Why Should I Support Her threads/or this post, The Case for Warren from the left(https://www.reddit.com/r/ElizabethWarren/comments/cjcguc/the_case_for_warren_from_the_left/)? I'm not tech savvy and not sure how difficult it is, but let us know what you guys think. Thanks again for making the plan bot!

**Comment by joegoldbeck** [comment]
This is a great request! Do you know if the desire is for someone to be able to call the bot with a trigger word, in the same way we do it now, or would they want the bot to just chime in automatically?

**Comment by joegoldbeck** [comment]
one thing I think we should be really mindful of is that we want the bot to improve discussion, not cut it off. So if we chime in with some earlier “why warren” threads, we should make sure we’re leaving lots of room for others to chime in with their reasons. The reasons might change over time, and that’d also give us more posts to link to!

As I’m starting to think through, I lean towards still requiring a trigger word. That leaves the discretion of when to bring in the bot up to humans who might have a good sense of the social dynamics around when to call it in versus reply with their own story :)

Also way easier to implement 🤣

**Comment by Hucxley** [comment]
I think trigger word is better, that's why I labeled it as an operation (the operation would have to be explicitly called). 

To "aim" the response at a specific comment asking the question, we'd have to also implement by either finding the parent of the calling comment, OR by parsing a "target" comment URL from the invoking comment to find the comment of the person who wants to know why to support Warren instead of the person who invoked the bot/operation (currently a pending issue).

**Comment by joegoldbeck** [comment]
This one got some love on our feature solicitation post https://www.reddit.com/r/ElizabethWarren/comments/dy6biy/soliciting_warrenplanbot_feature_requests/
