### ISSUE TITLE
download_plans.py doesn't download plans if OUTPUT_DIR doesn't exists

### ISSUE THREAD

**Issue by theship** [techforwarren/warren-plan-bot#129]
1. fork code and do a fresh install according to docker instructions
NOTE: [root]/data dir is empty (except for .gitignore file)
2. run
python scripts/download_plans.py
ACTUAL: returns
FileNotFoundError: [Errno 2] No such file or directory
EXPECTED: script calls os.makedirs(OUTPUT_DIR)
WORKAROUND:
make a data/raw/plan_html file or edit script to call os.makedirs(OUTPUT_DIR)
(I opted for the latter, see lines 21-30 & 102, in my fork
https://github.com/theship/warren-plan-bot/blob/master/scripts/download_plans.py)

**Comment by joegoldbeck** [comment]
Nice catch, and good fix! Would you like to make a PR with your change?

**Comment by Hucxley** [comment]
Fixed with #132
