### ISSUE TITLE
Pull Pushshift records into "Pending" state

### ISSUE THREAD

**Issue by Hucxley** [techforwarren/warren-plan-bot#86]
The idea here is to reply in two stages.

1) Get all the trigger posts we haven't seen before, and post them in firestore as "pending"
2) Go through all the pending posts in firestore and send replies

This would add some robustness in case the bot timed out while processing a post, for example.

One possible implementation:

- grab all pushift comments, and push them into a Firestore db of "pending replies".
- pop a few of them out each time the cloud function runs 
- if the pending db gets empty during a run, fill it back up the next time the function runs.
- when pulling from push shift, compare the IDs of the results in the pull to posts_replied_to and posts_pending_processing and ignore them if they're in either of those lists.
- might need a time_delta to make sure replies aren't sent to Reddit too fast to exceed rate limit.
- This would reduce any issues of timing out without finishing all posts at scale, since the pending list would just be waiting for the next cloud function cycle to pick up where the previous cycle left off.

**Comment by Hucxley** [comment]
Also, this would need a successful response from praw, or it would need to push post back into the pending stack.

If there was an error while making the response post to Reddit, but we didn't wait for success (or return without exception) before putting the post in posts db, then we'd have posts replied to entries that were incorrect (and would be skipped forevermore)

**Comment by joegoldbeck** [comment]
Looking at cleaning up the issues board so it's easier to find priority work to do, and I think we should close this for now! 

If we reach a scale where we start abandoning posts in a "processed" state (but without having actually properly replied), then we'll _definitely_ want to do something along these lines. However, we're not there yet, and I think we shouldn't add this complexity before we need it.

Can always reopen if it seems like a good idea later :D

**Comment by Hucxley** [comment]
Agreed
