### ISSUE TITLE
Add videos, prior interviews, and campaign speeches to potential plan matches.

### ISSUE THREAD

**Issue by Hucxley** [techforwarren/warren-plan-bot#88]
- as the campaign progresses, there will be significant video assets to work with as well, and they should be alternate sources for users who want to learn about Sen. Warren's plans.
- there are also older videos of her lectures and guest lectures that show where she comes from as a "policy wonk", and should be considered for labeling as potential matches for inquiries.

**Comment by joegoldbeck** [comment]
Looking at cleaning up the issues board, and I think we should close this!

We haven't gotten a request, and unless the campaign starts posting videos to link to plans, I don't think we should editorialize like that, personally. Can always reopen if it seems like a good idea later :D
